language: cpp
sudo: required

matrix:
    include:
        - os : linux
          dist: xenial
        - os : osx
          osx_image: xcode10.1

notifications:
  email:
    recipients:
    - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

addons:
    apt:
      update: true

before_script:
    - sudo apt install g++ cmake libboost-all-dev -y


script:
- cmake . && make -j4 && ctest --output-on-failure 

addons:
  apt:
    update: true
